#!/bin/bash

set -e

if [[ -f ./.glp ]]; then
  dir=$(head -n 1 .glp)
  if [[ -z $dir ]]; then
    echo 'go-localpath error: your .glp file is empty (it should contain the name of the vendor directory).'
    exit 1
  else
    if [[ ! -d $dir ]]; then
      echo "go-localpath error: the vendor directory indicated by .glp is $dir, but it does not exist."
      exit 1
    fi
  fi
  # Now I want to get the absolute path. readlink -f $dir does the trick on linux, but that relies on GNU
  # readlink.
  pushd $dir > /dev/null
  dir=`pwd -P`
  popd > /dev/null
  echo $dir
  export GOPATH=$dir
fi

go "$@"
